name: CMake Build Windows

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Create Build Environment
        shell: cmd
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: cmd
        working-directory: ${{runner.workspace}}/build
        run: cmake %GITHUB_WORKSPACE% -DCMAKE_BUILD_TYPE=%BUILD_TYPE%

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: cmd
        run: cmake --build . --config %BUILD_TYPE%
